keyutils: Fixes building with musl libc
Fixed a following build issue by including <limits.h> for UINT_MAX:
| key.dns_resolver.c: In function 'afsdb_hosts_to_addrs':
| key.dns_resolver.c:374:21: error: 'UINT_MAX' undeclared (first use in this
function)
|   unsigned int ttl = UINT_MAX, rr_ttl;
|                      ^~~~~~~~
| key.dns_resolver.c:374:21: note: each undeclared identifier is reported
only once for each function it appears in
| key.dns_resolver.c: In function 'dns_query_afsdb':
| key.dns_resolver.c:456:22: error: 'ULONG_MAX' undeclared (first use in
this function)
|   unsigned long ttl = ULONG_MAX;

This patch is back-ported from keyutils upstream, since the 1.5.9 is still
the latest release.

Signed-off-by: Ming Liu <peter.x.liu@external.atlascopco.com>